### ISSUE TITLE
Write test cases for get_products method

### ISSUE THREAD

**Issue by WesPainter** [DevOps-Shopcarts-S17/devops-shopcarts-s17#62] opened 2017-03-29 21:16 UTC
**As a** developer
**I need** test cases for the get_products method of shopcart.py
**So that** When I make changes, I can run tests to verify integrity of get_products method

**Assumptions:** 
* Test cases will be written in PyUnit syntax
* Test cases will reside in test_shopcart.py

**Acceptance Criteria:**
```
Given test cases written in test_shopcart.py
When I run python coverage with the test cases
Then at least 95% of the get_products method should be covered in the test
```

**Comment by Pratik-Karnik** [comment] 2017-04-04 19:23
Is this a duplicate of #95? @WesPainter @ceciliazhang12 @jiweix

**Comment by WesPainter** [comment] 2017-04-04 19:25
You are right, I misread the open issue as get_product and didn't see get_products in completed.

**Comment by Pratik-Karnik** [comment] 2017-04-04 19:27
So I think this is a duplicate then.

**Comment by WesPainter** [comment] 2017-04-04 19:27
@ceciliazhang12 I hope you didn't get too far on this.

**Comment by ceciliazhang12** [comment] 2017-04-04 19:30
It's ok, I just began. So maybe we should close this one instead?

**Comment by Pratik-Karnik** [comment] 2017-04-04 19:31
@ceciliazhang12 Yes lets do that!!

**Comment by Pratik-Karnik** [comment] 2017-04-04 19:31
Closing as duplicated by #95

**Closed as completed by Pratik-Karnik** 2017-04-04 19:31 UTC
Labels: enhancement
